Resources:
http://cs109.github.io/2014/ 

In [2]:
2*10

20

In [3]:
2**10

1024

In [4]:
name = "Ian"
name

'Ian'

In [5]:
world = 'That \' s'

In [6]:
world

"That ' s"

In [7]:
full = name + world

In [8]:
full

"IanThat ' s"

In [9]:
full = name + " " + world
full

"Ian That ' s"

In [10]:
len(full)

12

In [11]:
mylist = [1,2,7,8,9]
mylist

[1, 2, 7, 8, 9]

In [12]:
len(mylist)

5

In [13]:
mylist[0]

1

In [14]:
mylist[3]

8

http://pythontutor.com/

In [15]:
mylist[-1] ## last element 

9

In [16]:
mylist[-2] ## last two element

8

In [17]:
anotherlist = ['Ian', 74,34,2.14,2,True,42]

In [18]:
anotherlist

['Ian', 74, 34, 2.14, 2, True, 42]

In [19]:
mylist.append(52) #add new value using append
mylist

[1, 2, 7, 8, 9, 52]

In [20]:
mylist.append(120)

In [21]:
mylist[3] =  999 ## change value
mylist

[1, 2, 7, 999, 9, 52, 120]

In [22]:
del mylist[4] ## delete element
mylist

[1, 2, 7, 999, 52, 120]

In [23]:
anotherlist

['Ian', 74, 34, 2.14, 2, True, 42]

In [24]:
help(anotherlist)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      x.__add__(y) <==> x+y
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x
 |  
 |  __delitem__(...)
 |      x.__delitem__(y) <==> del x[y]
 |  
 |  __delslice__(...)
 |      x.__delslice__(i, j) <==> del x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __eq__(...)
 |      x.__eq__(y) <==> x==y
 |  
 |  __ge__(...)
 |      x.__ge__(y) <==> x>=y
 |  
 |  __getattribute__(...)
 |      x.__getattribute__('name') <==> x.name
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __getslice__(...)
 |      x.__getslice__(i, j) <==> x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __gt__(...)
 |      x.__gt__(y) <==> x>y
 |  
 |  __iadd__(...)
 |      x.__iadd__(y) <==> x+=y
 |  
 |  __imul__(...)
 |      x.__imul__(y) <==

In [25]:
dir(anotherlist)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [26]:
mylist.pop() # remove the last element

120

In [27]:
mylist

[1, 2, 7, 999, 52]

In [28]:
x = mylist.pop()

In [29]:
x

52

In [30]:
mylist

[1, 2, 7, 999]

In [31]:
mylist.extend([42,32, 66, 98]) ## concate list to another list 

In [32]:
mylist

[1, 2, 7, 999, 42, 32, 66, 98]

In [33]:
anotherlist.append([42, 32, 66, 98]) ## [42,32,66,98] as a list element in anotherlist, not concate two lists


In [34]:
anotherlist


['Ian', 74, 34, 2.14, 2, True, 42, [42, 32, 66, 98]]

In [35]:
mylist[0:3] # not include the mylist[3]

[1, 2, 7]

In [36]:
mylist[0:3] + mylist[3:6]

[1, 2, 7, 999, 42, 32]

In [37]:
mylist[0:6] # same as before 

[1, 2, 7, 999, 42, 32]

In [38]:
mylist[3:8]

[999, 42, 32, 66, 98]

In [39]:
mylist[:8] # start from begining up to 8 but not including 8th element 

[1, 2, 7, 999, 42, 32, 66, 98]

In [40]:
mylist[3:]

[999, 42, 32, 66, 98]

In [41]:
mylist[3:len(mylist)]

[999, 42, 32, 66, 98]

In [42]:
mylist[-5:-2] ## up to -2 not including -2 

[999, 42, 32]

In [43]:
mylist

[1, 2, 7, 999, 42, 32, 66, 98]

In [44]:
mylist[3]

999

In [45]:
mylist[4]

42

In [46]:
mylist[4:4] # starting 4 up to 4 but not incluidng 4, so empty

[]

In [47]:
mylist[4:4] = [12, 13, 14]

In [48]:
mylist

[1, 2, 7, 999, 12, 13, 14, 42, 32, 66, 98]

In [49]:
mylist[4] = [40, 50, 60]

In [50]:
mylist

[1, 2, 7, 999, [40, 50, 60], 13, 14, 42, 32, 66, 98]

In [51]:
mylist.index(999)

3

In [52]:
mylist

[1, 2, 7, 999, [40, 50, 60], 13, 14, 42, 32, 66, 98]

In [53]:
mylist.append(999)

In [54]:
mylist.index(999) ## only return the first occurence

3

In [55]:
mytup = ('a', 'b', 'c') # tuple is inmutable

In [56]:
mytup

('a', 'b', 'c')

In [57]:
mytup[2] ## always use [] index

'c'

In [58]:
len(mytup)

3

In [59]:
vector = (7.2, 5.5, 3.6)

In [60]:
vector

(7.2, 5.5, 3.6)

In [61]:
x,y,z = vector ## exactly match tuple length

In [62]:
x

7.2

In [63]:
y

5.5

In [64]:
z

3.6

In [65]:
vector = 7.2, 5.5, 3/6

In [66]:
vector

(7.2, 5.5, 0)

In [67]:
mydict = {42: "Ian",
         78: "Sokes-Rees"}

In [68]:
mydict

{42: 'Ian', 78: 'Sokes-Rees'}

In [69]:
mydict[42]

'Ian'

In [70]:
mydict[9]

KeyError: 9

In [71]:
mydict[0]

KeyError: 0

In [72]:
mydict = {'day': "Friday",
         'year':2013,
         "month":"Septerber"}

In [73]:
mydict['day'] ## string 

'Friday'

In [74]:
mydict[day]

NameError: name 'day' is not defined

In [75]:
mydict['month']

'Septerber'

In [76]:
mydict['year']

2013

In [77]:
mydict = dict(day = 'Friday', year = 2013, month = 'September') # dict function create dictionary 

In [78]:
mydict

{'day': 'Friday', 'month': 'September', 'year': 2013}

In [79]:
mytest = dict(12 = "iAN") ## dict function not allow numerical as key


SyntaxError: keyword can't be an expression (<ipython-input-79-aaabc901575a>, line 1)

In [81]:
mydict['time'] = "12.pm" # add new key to dictionay

In [82]:
mydict

{'day': 'Friday', 'month': 'September', 'time': '12.pm', 'year': 2013}

In [83]:
mylist

[1, 2, 7, 999, [40, 50, 60], 13, 14, 42, 32, 66, 98, 999]

In [84]:
del mylist[4]

In [85]:
mylist

[1, 2, 7, 999, 13, 14, 42, 32, 66, 98, 999]

In [86]:
len(mylist)

11

In [87]:
for num in mylist: # iterate in container mylist : not code like R: for i in 1:len(mylist)!!!
    print num

1
2
7
999
13
14
42
32
66
98
999


In [89]:
newlist = []
for num in mylist: ## num return each individual result
    newlist.append(num*5)

In [91]:
newlist

[5, 10, 35, 4995, 65, 70, 210, 160, 330, 490, 4995]

## Functions

In [92]:
def pow2(x):  ## def define function: pow2: name of function:
    return x**2

In [94]:
pow2(5)

25

In [95]:
def add_dashes(s,n=10):
    newstr = s + "-"*n
    return newstr

In [96]:
add_dashes('example')

'example----------'

In [97]:
add_dashes('foo',30)

'foo------------------------------'

In [98]:
title = add_dashes('foo',30)
title

'foo------------------------------'

## Modules

In [99]:
sin(1.6)

NameError: name 'sin' is not defined

In [100]:
import math
math.sin(1.6)

0.9995736030415051

In [101]:
import numpy as np ## as: give numpy a alis 
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [102]:
type(x)

numpy.ndarray

In [103]:
x.dtype


dtype('int64')

In [104]:
x.size


5

In [105]:
x + 10

array([11, 12, 13, 14, 15])

In [106]:
y = np.power(x,2)

In [107]:
y

array([ 1,  4,  9, 16, 25])

In [108]:
x**2

array([ 1,  4,  9, 16, 25])

In [109]:
x + y

array([ 2,  6, 12, 20, 30])