Resources:
https://github.com/jrjohansson/scientific-python-lectures 

## Classes 
- Each class method should have an argument self as it first argument. 
- \__init\__: The name of the method that is invoked when theobject is first created
- \__str\__: A method that is invoked when a simple string representation of the class is needed, as for example when printed


In [3]:
class Point:
    """
    simple class for representing a point in a 
    Cartesian coordinate system.
    """
    
    def __init__(self, x, y):
        """
        Creat a new point at x, y.
        """
        self.x = x
        self.y = y
    
    def translate(self, dx, dy):
        """
        Translate the point by dx and dy in the x and y direction
        """ 
        self.x += dx
        self.y += dy
    
    def __str__(self):
        return("Point at [%f, %f]" %(self.x, self.y))
        

In [8]:
p1 = Point(0, 0) ## this will invokde the __init__ method in the Point class
print(p1)

Point at [0.000000, 0.000000]


In [9]:
p2 = Point(1, 1)
p1.translate(0.25, 1.5)

print(p1)
print(p2)

Point at [0.250000, 1.500000]
Point at [1.000000, 1.000000]


## Unnamed functions(lambda function)
In python we can also create unnamed functions, using the lambda keyword:

In [11]:
f1 = lambda x: x**2
# is equivalent ot 
def f2(x):
    return x**2

In [12]:
f1(2), f2(2)

(4, 4)

This technique is useful for example when we want to pass a simple function as an argument to another function, like this:

In [13]:
# map is a built-in python function
map(lambda x: x**2, range(-3,4))

[9, 4, 1, 0, 1, 4, 9]

## Default argument and keyword arguments
In a definition of a function, we can give default values to the arguments the function takes:

In [17]:
def myfunc(x, p=2, debug = False):
    if debug:
        print("evaluating myfunc for x = " + 
              str(x) + " using exponent p = " + str(p))
    return x**p

In [18]:
myfunc(5)

25

In [20]:
myfunc(5, debug = True)

evaluating myfunc for x = 5using exponent p = 2


25

if we explicitly list the name of the arguments in the function calls, they do not need to come i nthe same order as in the function definition. This is called keyword arguments, and is oftern very useful in functions that takes a lot of optional arguments

In [21]:
myfunc(p = 3, debug=True, x = 7)

evaluating myfunc for x = 7using exponent p = 3


343

we can return multiple values from a function using tuples

In [22]:
def powers(x):
    """
    Return a few powers of x.
    """
    return x ** 2, x ** 3, x **4

In [23]:
powers(3)

(9, 27, 81)

In [24]:
x2, x3, x4 = powers(3)
print(x3)

27


## Loops
In python, loops can be programmed in a number of different ways. The most common is the for loop, which is used together with iterable objects, such as lists.

In [25]:
for x in [1, 2, 3]:
    print(x)

1
2
3


The for loop iterates over the elements of the supplied list, and executes the containing block once for each element. 

In [26]:
for x in range(4): # by default range start at 0
    print(x)

0
1
2
3


In [27]:
for x in range(-3,3):
    print(x)

-3
-2
-1
0
1
2


In [28]:
for word in ['scientific', 'computing', 'with','python']:
    print(word)

scientific
computing
with
python


To iterate over key-value pairs of a dictionary:

In [29]:
params = {"parameter1" : 1.0,
          "parameter2" : 2.0,
          "parameter3" : 3.0,}

for key, value in params.items():
    print(key + " = " + str(value))

parameter1 = 1.0
parameter3 = 3.0
parameter2 = 2.0


## Numpy - multidimensional data arrays

In [30]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Introduction
The numpy package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized.
To use numpy need to import the module it using of example:


In [31]:
from numpy import *

In the numpy package the terminology used for vectors, matrices and higher-dimensional data sets is array

## Creating numpy arrays
There are a number of ways to initialize new numpy arrays, for example from
- a Python list or tuples
- using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc
- reading data from files

**From lists**


for example, to creat new vector and matrix arrays from Python lists we can use the numpy.array function

In [32]:
# a vector: the argument to the array function is a Python list
v = array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [33]:
# a matrix: the argument to the array function is a nested Python list
M = array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The v and M objects are both of the type ndarry that the numpy module provides


In [34]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the v and M arrays is only their shapes

In [35]:
v.shape

(4,)

In [36]:
M.shape

(2, 2)

The number of elements in the array is available through the ndarray.size property:

In [37]:
M.size

4

Why not simply use Python lists for computations instead of creating a new array type?
- Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing
- Numpy arrays are ** statically typed** and **homogeneous**. The type of the elements is determined when array is created.
- Numpy arrays are memory efficient
- Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a complied language (C and Fortran is used).

In [38]:
M.dtype

dtype('int64')

In [39]:
M[0,0] = "Hello"

ValueError: invalid literal for long() with base 10: 'Hello'

we get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [40]:
M = array([[1, 2], [3, 4]], dtype = complex)

In [41]:
M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Common type that can be used with dtype are: int, float, complex, bool, object, etc. 

We can also explicitly define the bit size of the data types, for example: int64, int16



## Using array-generating functions
For larger arrays it is inpractical to initialize the data manually, using explicity python lists. Instead we can use one of the many functions in numpy that generates arrays of different forms. Some of the more common are:

**arange**

In [42]:
# create a range
x = arange(0, 10, 1) # arguments: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x = arange(-1, 1, 0.1)
x

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01])

**linspace and logspace**


In [45]:
# using linspace, both end points ARE included 
linspace(0, 10, 25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [46]:
logspace(0, 10, 10, base = e)

array([  1.00000000e+00,   3.03773178e+00,   9.22781435e+00,
         2.80316249e+01,   8.51525577e+01,   2.58670631e+02,
         7.85771994e+02,   2.38696456e+03,   7.25095809e+03,
         2.20264658e+04])

**mgrid**

In [49]:
x, y = mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [50]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

** random data**

In [51]:
from numpy import random

In [52]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[ 0.48718294,  0.53291316,  0.11942549,  0.78902505,  0.68846758],
       [ 0.24991282,  0.39636828,  0.89525305,  0.62262866,  0.45510791],
       [ 0.25744496,  0.02360026,  0.29632951,  0.1413357 ,  0.53652678],
       [ 0.59471176,  0.64169911,  0.36200541,  0.45134684,  0.58610947],
       [ 0.53864598,  0.13426629,  0.23039946,  0.10200663,  0.10923084]])

In [53]:
# standard normal distribution random numbers
random.randn(5,5)

array([[-2.54338727, -0.1184288 ,  0.59303697, -0.44733826, -2.88191892],
       [ 0.40491508, -0.90807276, -0.16686996, -0.58714017,  0.67025163],
       [ 0.16753712,  1.25245835, -0.50702427, -0.20413697,  1.43662968],
       [-0.05407622, -0.36179429, -1.14869779,  0.81304308,  0.23288452],
       [ 0.82870928, -1.1237892 , -0.98523535,  0.06173886,  0.2399299 ]])

**diag**

In [54]:
# a diagonal matrix
diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [55]:
# diagonal with offset from the main diagonal
diag([1, 2, 3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

** zeros and ones**


In [56]:
zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [1]:
ones((3,3))

NameError: name 'ones' is not defined

## File I/O

## Comma-separated values (CSV)

A very common file format for data files are the comma-separated values(CSV), or related format such as TSV(tab-separated values). To read data from such file into Numpy arrays we can use the numpy.genfromtxt function. For example

In [11]:
!head stockholm_td_adj.dat

head: cannot open ‘stockholm_td_adj.dat’ for reading: No such file or directory


In [12]:
data = genfromtxt('stockholm_td_adj.dat.txt')

NameError: name 'genfromtxt' is not defined

## Exceptions

In python errors are managed with a special language construct called "Exceptions". To generate an exception we could use the raise state ment, which takes an argument that must be an instance of the class BaseException or a class derived from it

In [2]:
raise Exception("description of the error")

Exception: description of the error

A typical use of exceptions is to about functions when some error condition occurs, for example:

def my_function(arguments):
    if not verify (arguments):
        raise Exception("Invalid arguments")
     # rest of the code goes here
     
     
To gracefully catch erros that are generated by functions and class methods, or by the Python interpreter itself, use the try and excep satements:

  try:
      # normal code goes here
  except:
      # code for error handling goes here
      # this code is not executed unless the code
      # above generated an error 
      

In [3]:
try:
    print("test")
    #generate an error: the variable test is not defined
    print(test)
except:
    print("Caught an exception")

test
Caught an exception


In [9]:
try:
    print("test")
    #generate an error: the variable test is not defined
    print(test)
except Exception as e:
    print("Caught an exception:" + str(e))

test
Caught an exception:name 'test' is not defined
